package com.legaldocs.eas.analysis;

public enum ClauseType {
    TERMINATION,
    NOTICE_PERIOD,
    COMPENSATION,
    WORK_HOURS,
    CONFIDENTIALITY,
    NON_COMPETE,
    NON_SOLICITATION,
    INTELLECTUAL_PROPERTY,
    LEAVE_POLICY,
    PROBATION,
    GOVERNING_LAW,
    JURISDICTION,
    DISPUTE_RESOLUTION,
    INDEMNIFICATION,
    LIABILITY,
    DATA_PROTECTION,
    ASSIGNMENT,
    AMENDMENT,
    FORCE_MAJEURE,
    OTHER
}
